# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "75fabf5d369d56d68571b0accd4fd4a0"
name = "Video email app 0v1"
application_url = "https://video-email-shopify-0v1.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "checkouts/create" ]
  uri = "/webhooks/checkouts/create"

  [[webhooks.subscriptions]]
  topics = [ "checkouts/update" ]
  uri = "/webhooks/checkouts/update"

  [[webhooks.subscriptions]]
  topics = [ "carts/create" ]
  uri = "/webhooks/carts/create"

  [[webhooks.subscriptions]]
  topics = [ "carts/update" ]
  uri = "/webhooks/carts/update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders,write_metaobjects,read_metaobjects,write_customers,read_customers"

[auth]
redirect_urls = [ "https://video-email-shopify-0v1.onrender.com/api/auth" ]
